### ISSUE TITLE
无法使用 执行命令错误

### ISSUE THREAD

**Issue by helloMJW** [hyperf/swagger#5]
```
root@cd6db4504bc0:/var/www/skeleton# php bin/hyperf.php swagger:gen
[DEBUG] Event Hyperf\Framework\Event\BootApplication handled by Hyperf\Config\Listener\RegisterPropertyHandlerListener listener.
[DEBUG] Event Hyperf\Framework\Event\BootApplication handled by Hyperf\ExceptionHandler\Listener\ErrorExceptionHandler listener.
[DEBUG] Event Hyperf\Framework\Event\BootApplication handled by Hyperf\Paginator\Listener\PageResolverListener listener.
[DEBUG] Event Hyperf\Framework\Event\BootApplication handled by Hyperf\ExceptionHandler\Listener\ExceptionHandlerListener listener.
[DEBUG] Event Hyperf\Framework\Event\BootApplication handled by Hyperf\DbConnection\Listener\RegisterConnectionResolverListener listener.
PHP Fatal error:  Uncaught ErrorException: Invalid argument supplied for foreach() in /var/www/skeleton/vendor/hyperf/swagger/src/Command/GenCommand.php:30
Stack trace:
#0 /var/www/skeleton/vendor/hyperf/swagger/src/Command/GenCommand.php(30): Hyperf\ExceptionHandler\Listener\ErrorExceptionHandler->Hyperf\ExceptionHandler\Listener\{closure}(2, 'Invalid argumen...', '/var/www/skelet...', 30, Array)
#1 /var/www/skeleton/vendor/zircote/swagger-php/src/Analysis.php(466): Hyperf\Swagger\Command\GenCommand->Hyperf\Swagger\Command\{closure}(Object(OpenApi\Analysis))
#2 /var/www/skeleton/vendor/zircote/swagger-php/src/functions.php(57): OpenApi\Analysis->process(Array)
#3 /var/www/skeleton/vendor/hyperf/swagger/src/Command/GenCommand.php(45): OpenApi\scan('app/')
#4 /var/www/skeleton/vendor/hyperf/utils/src/Functions.php(275): Hyperf\Swagger\Command\GenCommand->handle()
#5 /var/www/skeleton/vendor/hyperf/command/src/Command.php(436): call(Array)
#6 {main}
  thrown in /var/www/skeleton/vendor/hyperf/swagger/src/Command/GenCommand.php on line 30

Fatal error: Uncaught ErrorException: Invalid argument supplied for foreach() in /var/www/skeleton/vendor/hyperf/swagger/src/Command/GenCommand.php:30
Stack trace:
#0 /var/www/skeleton/vendor/hyperf/swagger/src/Command/GenCommand.php(30): Hyperf\ExceptionHandler\Listener\ErrorExceptionHandler->Hyperf\ExceptionHandler\Listener\{closure}(2, 'Invalid argumen...', '/var/www/skelet...', 30, Array)
#1 /var/www/skeleton/vendor/zircote/swagger-php/src/Analysis.php(466): Hyperf\Swagger\Command\GenCommand->Hyperf\Swagger\Command\{closure}(Object(OpenApi\Analysis))
#2 /var/www/skeleton/vendor/zircote/swagger-php/src/functions.php(57): OpenApi\Analysis->process(Array)
#3 /var/www/skeleton/vendor/hyperf/swagger/src/Command/GenCommand.php(45): OpenApi\scan('app/')
#4 /var/www/skeleton/vendor/hyperf/utils/src/Functions.php(275): Hyperf\Swagger\Command\GenCommand->handle()
#5 /var/www/skeleton/vendor/hyperf/command/src/Command.php(436): call(Array)
#6 {main}
  thrown in /var/www/skeleton/vendor/hyperf/swagger/src/Command/GenCommand.php on line 30
```

**Comment by limingxinleo** [comment]
swagger可以用 apidog 那个组件，也是Hyperf组核心开发成员做的
